openapi: 3.2.0
info:
  description: Cataloguing API.
  version: API V
  title: Cataloguing Audit Controller API
  termsOfService: Terms of service
  contact:
    name: Mani Bhushan
    url: www.geniemode.com
    email: mani.kumar@geniemode.com
  license:
    name: License of API
    url: API license URL
servers:
- url: https://portal.geniemode.com
tags:
- name: audit-controller
  description: Audit Controller
paths:
  /api/v1/audit/tna/done-count:
    get:
      tags:
      - audit-controller
      summary: tnaDoneCount
      operationId: tnaDoneCountUsingGET
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
        '403':
          description: Forbidden!!!!!
        '500':
          description: 500 message
